# короткие названия палитр по картинкам: en, ru, lv
T = {
'2019-pigeon-polly-writing-diploma': ('Thesis season', 'Сессия и диплом', 'Diplomdarba laiks'),
'2022-pigeon-polly-celebrates-dia-de-muertos': ('Día de Muertos', 'День мёртвых', 'Mirušo diena'),
'2022-pigeon-polly-celebrates-new-year-first-time-in-the-bed': ('New Year in bed', 'Новый год в кровати', 'Jaunais gads gultā'),
'2022-pigeon-polly-graphic-designer': ('Make the logo bigger', 'Сделайте логотип побольше', 'Lielāku logo'),
'2022-pigeon-polly-started-own-small-business': ('Ice cream van summer', 'Лето с фургоном мороженого', 'Saldējuma busiņa vasara'),
'2022-pigeon-polly-summer-lover': ('Beach day', 'День на пляже', 'Pludmales diena'),
'2023-pigeon-polly-against-war': ('Wrapped in a blanket', 'Завернуться в одеяло', 'Ietinies segā'),
'2023-pigeon-polly-celebrates-new-year': ('Cake and a laptop', 'Торт и ноутбук', 'Kūka un dators'),
'2023-pigeon-polly-thinking-about-relocation-to-mars': ('Sunflowers on Mars', 'Подсолнухи на Марсе', 'Saulespuķes uz Marsa'),
'2024-pigeon-polly-bath-relax': ('Bath time blues', 'Синяя ванная', 'Zilā vanna'),
'2025-pigeon-polly-celebrates-new-year': ('Pyjama party', 'Пижамная вечеринка', 'Pidžamu ballīte'),
'2025-pigeon-polly-romantizing-coffee-and-trains-in-autumn-vibes': ('Night train in October', 'Ночной поезд в октябре', 'Nakts vilciens oktobrī'),
'2026-pigeon-polly-accidentaly-drinked-brush-watercolor-water': ('Brush water', 'Вода из-под кисточки', 'Otas ūdens'),
'2026-pigeon-polly-and-rat-tuna-are-scared-of-last-news-about-drones-and-hantavirus': ('Breaking news', 'Срочные новости', 'Jaunākās ziņas'),
'2026-pigeon-polly-fancy-life': ('Fancy life', 'Шикарная жизнь', 'Grezna dzīve'),
'2026-pigeon-polly-fired-changing-remote-work-to-office-job-after-6-years': ('Back to the office', 'Снова в офис', 'Atpakaļ birojā'),
'2026-pigeon-polly-keeps-busy-living': ('Five minutes of peace', 'Пять минут тишины', 'Piecas miera minūtes'),
'2026-pigeon-polly-sam-milka-cat-and-horse-of-the-year-celebrates-new-year': ('New Year’s Eve at home', 'Новогодний вечер дома', 'Vecgada vakars mājās'),
'2026-pigeon-polly-seven-years-later': ('Seven years later', 'Семь лет спустя', 'Septiņus gadus vēlāk'),
'2024-detective-mr-titos-in-the-office-late-night': ('The night shift', 'Ночная смена', 'Nakts maiņa'),
'halloween-cup': ('Haunted tea', 'Чай с привидениями', 'Spoku tēja'),
'halloween-in-blue': ('The Pumpkin butler', 'Тыквенный дворецкий', 'Ķirbju sulainis'),
'halloween-lady': ('Victorian pumpkin', 'Викторианская тыква', 'Viktorijas laika ķirbis'),
'halloween-poirot': ('Monsieur Pumpkin', 'Месье Тыква', 'Monsieur Ķirbis'),
'2023-mr-chew-australian-postal-snail-introduction': ('Postal snail', 'Почтовая улитка', 'Pasta gliemezis'),
'2023-mr-chew-be-careful-on-the-road': ('Mind the road', 'Осторожно, дорога', 'Uzmanies uz ceļa'),
'2023-mr-chew-be-careful-on-the-road-ii': ('Traffic cone', 'Дорожный конус', 'Ceļa konuss'),
'2023-mr-chew-booklyne-nine-nine-edition': ('Precinct nine-nine', 'Участок девять-девять', 'Iecirknis 99'),
'2023-mr-chew-coffee-passion': ('More coffee', 'Больше кофе', 'Vairāk kafijas'),
'2023-mr-chew-delivery': ('Balloon delivery', 'Доставка на шариках', 'Piegāde ar baloniem'),
'2023-mr-chew-halloween-edition': ('Bat wings', 'Крылья летучей мыши', 'Sikspārņa spārni'),
'2023-mr-chew-lgbtq-edition': ('On stage', 'На сцене', 'Uz skatuves'),
'2023-mr-chew-take-away-coffee': ('Coffee to go', 'Кофе с собой', 'Kafija līdzņemšanai'),
'2024-halloween-edition': ('Witch hat', 'Ведьмина шляпа', 'Raganas cepure'),
'2024-mr-chew-celebrates-new-year': ('Jo-ho-ho', 'Хо-хо-хо', 'Ho-ho-ho'),
'2024-mr-chew-celebrates-valentines-day': ('I snail you', 'Люблю тебя медленно', 'Mīlu tevi lēnām'),
'2024-mr-chew-dnd-edition': ('Roll for initiative', 'Бросок инициативы', 'Met iniciatīvu'),
'2024-mr-chew-gardening-edition': ('Slow garden', 'Медленный сад', 'Lēnais dārzs'),
'2024-mr-chew-rainbow-candy-edition': ('Rainbow candy', 'Радужная конфета', 'Varavīksnes konfekte'),
'2024-mr-chew-steamphunk-edition': ('Steampunk shell', 'Стимпанк-ракушка', 'Tvaikpanka mājiņa'),
'2025-mr-chew-opened-pumpkin-spice-latte-season': ('Pumpkin spice latte', 'Тыквенный латте', 'Ķirbju latte'),
'2025-mr-chew-travel-edition-can-you-find-polly': ('Suitcase shell', 'Ракушка-чемодан', 'Čemodāna mājiņa'),
'2025-sometimes-mr-chew-wants-to-be-retired': ('Knitting and apples', 'Вязание и яблоки', 'Adīšana un āboli'),
'sketchbook-1': ('Faces on a tram', 'Лица в трамвае', 'Sejas tramvajā'),
'sketchbook-2': ('People in ink', 'Люди тушью', 'Cilvēki tušā'),
'sketchbook-3': ('Swan studies', 'Этюды лебедей', 'Gulbju skices'),
'sketchbook-4': ('Street panorama', 'Панорама улицы', 'Ielas panorāma'),
'sketchbook-5': ('Cozy breakfast', 'Уютный завтрак', 'Mājīgas brokastis'),
'sketchbook-6': ('Garage number six', 'Гараж номер шесть', 'Garāža numur seši'),
'sketchbook-7': ('Rooftops and towers', 'Крыши и башни', 'Jumti un torņi'),
'sketchbook-8': ('Brick house', 'Кирпичный дом', 'Ķieģeļu māja'),
'sketchbook-9': ('Reading room', 'Комната для чтения', 'Lasītava'),
'sketchbook-10': ('Mon ami Poirot', 'Мон ами Пуаро', 'Mon ami Puaro'),
'sketchbook-11': ('Coffee press', 'Кофейный пресс', 'Kafijas prese'),
'sketchbook-12': ('Café corner', 'Уголок кафе', 'Kafejnīcas stūrītis'),
'sketchbook-13': ('Pastry counter', 'Витрина с выпечкой', 'Konditorejas vitrīna'),
'sketchbook-14': ('Red wall, green leaves', 'Красная стена, зелёные листья', 'Sarkana siena, zaļas lapas'),
'sketchbook-15': ('Northern berries', 'Северные ягоды', 'Ziemeļu ogas'),
'sketchbook-16': ('Wild strawberry', 'Земляника', 'Meža zemene'),
'sketchbook-17': ('Persimmon season', 'Сезон хурмы', 'Hurmas sezona'),
'sketchbook-18': ('The table before midnight', 'Стол перед полуночью', 'Galds pirms pusnakts'),
'sketchbook-19': ('One paint tube', 'Один тюбик краски', 'Viena krāsas tūbiņa'),
'sketchbook-20': ('Tram and lighthouse', 'Трамвай и маяк', 'Tramvajs un bāka'),
'sketchbook-21': ('Brushes in a mug', 'Кисти в кружке', 'Otas krūzē'),
'anxiety-1': ('Sprouts of anxiety', 'Ростки тревоги', 'Trauksmes asni'),
'anxiety-2': ('It arrives', 'Она приходит', 'Tā atnāk'),
'anxiety-3': ('Seethes', 'Кипит', 'Vārās'),
'anxiety-4': ('Wilts', 'Увядает', 'Novīst'),
'anxiety-5': ('Through the weight', 'Сквозь тяжесть', 'Caur smagumu'),
'anxiety-6': ('Not eternal', 'Не навсегда', 'Ne mūžīga'),
'anxiety-7': ('One can live again', 'Можно жить снова', 'Var dzīvot atkal'),
'challenge-pigeonpolly-cactus-4-10-2026': ('Daily challenge: cactus', 'Челлендж: кактус', 'Izaicinājums: kaktuss'),
}
