# Палитры, подобранные вручную (они же в пинах Pinterest): ключ картинки → [(en, ru, lv, hex)]
O = {
'2025-pigeon-polly-romantizing-coffee-and-trains-in-autumn-vibes': [('Beak Gold','Золотой клюв','Zelta knābis','#E9A72B'),('Puffer Jacket Rust','Ржавый пуховик','Rūsganā jaka','#87390E'),('Pumpkin Field','Тыквенное поле','Ķirbju lauks','#A57934'),('Jelly Cake Pink','Розовое желе','Želejas kūka','#CA7061'),('Donut Glaze Teal','Бирюзовая глазурь','Glazūras tirkīzs','#538E92'),('Sleepy Backpack Lilac','Сонный рюкзак','Miegainā mugursoma','#97758C')],
'sketchbook-17': [('Persimmon','Хурма','Hurma','#F2830B'),('Ripe Glow','Спелое сияние','Gatavs mirdzums','#DF420E'),('Tablecloth Teal','Бирюзовая скатерть','Galdauta tirkīzs','#2395A4'),('Faded Mint','Выцветшая мята','Izbalējusi piparmētra','#6FB9B6'),('Wooden Table','Деревянный стол','Koka galds','#996341'),('Cinnamon Stem','Коричный черенок','Kanēļa kāts','#74462E')],
'2022-pigeon-polly-started-own-small-business': [('Summer Sky','Летнее небо','Vasaras debesis','#40A5CE'),('Van Yellow','Жёлтый фургон','Dzeltenais busiņš','#FBAD29'),('Waffle Cone','Вафельный рожок','Vafeļu radziņš','#A46C24'),('Chocolate Scoop','Шоколадный шарик','Šokolādes bumbiņa','#8F6550'),('Roadside Grass','Трава у дороги','Ceļmalas zāle','#525923'),('Tire Black','Чёрная шина','Riepas melnais','#311D17')],
'2024-pigeon-polly-bath-relax': [('Bathroom Tile','Кафель','Vannas flīzes','#4B86AB'),('Deep Soak','Глубокая ванна','Dziļā vanna','#395879'),('Bubble Foam','Пена','Burbuļu putas','#AEC5D1'),('Steamy Mirror','Запотевшее зеркало','Aizsvīdis spogulis','#8095A9'),('Pigeon Plum','Голубиная слива','Baložu plūme','#604F55'),('Late Night Ink','Поздние чернила','Vēlā tinte','#2E383B')],
'2026-pigeon-polly-sam-milka-cat-and-horse-of-the-year-celebrates-new-year': [('Champagne','Шампанское','Šampanietis','#E3CFA9'),('Horse Mane','Конская грива','Zirga krēpes','#B17B44'),('Fir Tree','Ёлка','Egle','#5E6738'),('Roast Dinner','Праздничный ужин','Svētku vakariņas','#763E25'),('Cocoa','Какао','Kakao','#47371E'),('Midnight Wall','Полуночная стена','Pusnakts siena','#3B364C')],
'2024-mr-chew-gardening-edition': [('Clay Pot','Глиняный горшок','Māla pods','#ECD2B3'),('Terracotta','Терракота','Terakota','#A05C25'),('Potting Soil','Земля для рассады','Podu zeme','#826A4F'),('Garden Gloves','Садовые перчатки','Dārza cimdi','#A0876D'),('Olive Leaf','Оливковый лист','Olīvu lapa','#63542C'),('Rich Earth','Чернозём','Melnzeme','#3C2512')],
'2025-mr-chew-opened-pumpkin-spice-latte-season': [('Pumpkin Spice','Тыквенная пряность','Ķirbju garšviela','#D5330B'),('Burnt Cinnamon','Жжёная корица','Dedzināts kanēlis','#7C2C16'),('Latte Foam','Пенка латте','Lattes putas','#A26E3F'),('Denim Scarf','Джинсовый шарф','Džinsa šalle','#1E4C7A'),('Spooky Dusk','Жуткие сумерки','Baisā krēsla','#3B3746'),('Spider Web Black','Паутина','Zirnekļtīkls','#1C1922')],
'halloween-lady': [('Candle Wax','Свечной воск','Sveču vasks','#D6A86F'),('Gilded Frame','Золочёная рама','Zeltīts rāmis','#9B8057'),('Ghostly Teal','Призрачная бирюза','Spoku tirkīzs','#559487'),('Pumpkin Skin','Тыквенная корка','Ķirbja miza','#80451E'),('Haunted Wood','Заколдованное дерево','Spoku koks','#705E45'),('Attic Dust','Чердачная пыль','Bēniņu putekļi','#493B30')],
'2024-mr-chew-dnd-edition': [('Potion Green','Зелье','Dzira','#B3C34A'),('Goblin Moss','Гоблинский мох','Goblinu sūna','#7F933F'),('D20 Orange','Оранжевый D20','D20 oranžs','#D86D18'),('Wizard Grey','Серый маг','Burvja pelēks','#95948D'),('Tavern Wood','Дерево таверны','Kroga koks','#6C5D2B'),('Dungeon Dark','Тьма подземелья','Pazemes tumsa','#352713')],
'2019-pigeon-polly-writing-diploma': [('Desk Lamp','Настольная лампа','Galda lampa','#DC903A'),('Old Notes','Старые конспекты','Vecie konspekti','#E6B477'),('Toast','Тост','Grauzdiņš','#A0582B'),('Raspberry Deadline','Малиновый дедлайн','Aveņu termiņš','#AA2A43'),('Dorm Wall Red','Стена общежития','Kopmītņu siena','#742325'),('Midnight Panic','Полуночная паника','Pusnakts panika','#471717')],
'2022-pigeon-polly-summer-lover': [('Sea Breeze','Морской бриз','Jūras vējš','#94B8D2'),('Deep Blue','Глубокий синий','Dziļi zils','#3C638E'),('Warm Sand','Тёплый песок','Siltas smiltis','#E8BF77'),('Sun Hat','Шляпа от солнца','Saules cepure','#D18C2D'),('Driftwood','Плавник','Dreifkoks','#C5B091'),('Book Cover Red','Красная обложка','Sarkanais vāks','#7D392C')],
'sketchbook-15': [('Cloudberry Gold','Морошка','Lācenes zelts','#D4A24F'),('Lichen','Лишайник','Ķērpis','#A2A086'),('Bog Moss','Болотный мох','Purva sūna','#63665A'),('Rainy Forest','Дождливый лес','Lietains mežs','#3F4A51'),('Bark','Кора','Miza','#6B4B35'),('Northern Night','Северная ночь','Ziemeļu nakts','#0E1826')],
}
